### ISSUE TITLE
Remove globals

### ISSUE THREAD

**Issue by Mause** [spywhere/Javatar#23]
It's usually recommended to not use variables, as they make maintenance difficult.

I would recommend that you use a `Settings` singleton, similar to how you already have the `ActionList`, to store the state you currently store globally.

Though preferably something like this;
```py
class Settings(object):
    @classmethod
    def instance(cls):
        if not hasattr(cls, '_instance'):
             cls._instance = cls()
        return cls._instance
```

**Comment by spywhere** [comment]
The new core plugin is now finished and pushed. There're still many classes to be coded, mostly Java related classes.

I think this issue can be closed right now (as I closed it) since the new code utilise your suggestion heavily. If you have any code comment/suggestion just reply and/or open the issue up again.

PS. I will use this issue as a developers' talk or anything related to the code from now on
