### ISSUE TITLE
File is not compiled

### ISSUE THREAD

**Issue by eickhardt** [spywhere/Javatar#45]
I'm having trouble following the guide found here: http://javatar.readthedocs.org/en/latest/getting_started.html

Everything goes well untill I reach the final step "Running Our Code". Here I get an instant error that says "File is not compiled". I'm a Java noob aswell, but I'm guessing there should be something in the '/bin/javatar/simple/demo' folder, but it's empty. Any help would be greatly appreaciated.

My action history:

### System Informations
* Javatar Version: `1.0.0`
* Sublime Version: `3083`
* Package Path: `C:\Users\Daniel\AppData\Roaming\Sublime Text 3\Packages`
* Javatar Channel: `stable`
* Sublime Channel: `stable`
* Is Debug Mode: `False`
* Platform: `windows`
* As Packages: `True`
* Package Control: `True`
* Architecture: `x64`
* Javatar's Parent Folder: `Javatar`
* Is Project: `True`
* Is File: `True`
* Is Java: `True`

### Action List
1. Startup
2. Reset all settings
3. Reset all snippets
4. Reset all default packages
5. Read settings
6. Load snippets
7. Check news
8. Ready
9. Javatar snippet Class.javatar loaded
10. Analyse snippet [file=Packages/Javatar/snippets/Class.javatar]
11. Javatar snippet Enumerator.javatar loaded
12. Analyse snippet [file=Packages/Javatar/snippets/Enumerator.javatar]
13. Javatar snippet Interface.javatar loaded
14. Analyse snippet [file=Packages/Javatar/snippets/Interface.javatar]
15. Load Java default packages
16. Javatar default package Proto.javatar-packages loaded
17. Analyse package [file=Packages/Javatar/Developers/Proto.javatar-packages]
18. Javatar default package JavaSE8.javatar-packages loaded
19. Analyse package [file=Packages/User/JavaSE8.javatar-packages]
20. Check packages update
21. Select item ['Builds...', 'Build system'] [from_sublime=True]
22. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
23. Build [build_type=project]
24. Build all
25. Building Finished [0.93s]
26. Select item ['Builds...', 'Build system'] [from_sublime=False]
27. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
28. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
29. Build [build_type=project]
30. Build all
31. Building Finished [0.92s]
32. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
33. Select item ['Builds...', 'Build system'] [from_sublime=False]
34. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
35. Build [build_type=project]
36. Build all
37. Building Finished [0.93s]
38. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
39. Build [build_type=project]
40. Build all
41. Building Finished [0.93s]
42. Select item ['Builds...', 'Build system'] [from_sublime=False]
43. Select item ['Current Class', 'Build current class'] [from_sublime=False]
44. Build [build_type=class]
45. Build file
46. Building Finished [0.93s]
47. Exit menu [from_sublime=False]
48. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=True]
49. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
50. Build [build_type=project]
51. Build all
52. Building Finished [0.92s]
53. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
54. Select item ['Javatar Settings...', 'Adjust Javatar settings'] [from_sublime=False]
55. Select item ['Set Default JDK', 'Set default JDK for builds and runs'] [from_sublime=False]
56. Project Settings [type=set_jdk]
57. Select item ['Builds...', 'Build system'] [from_sublime=False]
58. Exit menu [from_sublime=False]
59. Select item ['Builds...', 'Build system'] [from_sublime=True]
60. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
61. Select item ['Builds...', 'Build system'] [from_sublime=False]
62. Select item ['Project', 'Build all classes in project'] [from_sublime=False]
63. Build [build_type=project]
64. Build all
65. Building Finished [1.23s]
66. Select item ['Builds...', 'Build system'] [from_sublime=False]
67. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
68. Select item ['Help and Support...', 'Utilities for Help and Support on Javatar'] [from_sublime=False]
69. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=False]
70. Select item ['Builds...', 'Build system'] [from_sublime=False]
71. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
72. Select item ['Builds...', 'Build system'] [from_sublime=False]
73. Select item ['Run Main Class', 'Run class contains main method'] [from_sublime=False]
74. Select item ['Builds...', 'Build system'] [from_sublime=False]
75. Exit menu [from_sublime=False]
76. Select item ['Help and Support...', 'Utilities for Help and Support on Javatar'] [from_sublime=True]
77. Select item ['Actions History', 'Generate a report on Javatar actions history'] [from_sublime=False]

I think your plugin is awesome, and I really want to use it. My apologies if I have overlooked something obvious.

**Comment by spywhere** [comment]
First of all, from the action list, seems like you try to restart Sublime Text and try again. That's a good idea to do but unfortunately, that also remove most of the commands you already done in that session.

So, in order to solve this issue, could you please send me the following things?

1. A screenshot of Sublime Text before compile your code.
2. A Sublime Text's console log after compile your code.

**Comment by eickhardt** [comment]
Thank you for your swift reply.

Your suggestion prompted me to start over from scratch without restarting sublime, and that did the trick. After deleting all files and going through the guide again, my program compiled and asked me what my name is. You deserve all the internet points I can give! Thank you. The only two messages that where in my console are:


Does this mean however that there are certain times when I should not restart sublime to avoid this?

**Comment by spywhere** [comment]
Yes, if you are working with a new project but not save it to the (.sublime-project) file yet, when you open the project second time, the changes and settings on that particular project might be lost too (since Sublime Text did not preserve the project data on quit).

This project data contains some Javatar project settings including Source Folder, Target JDK or Dependencies which leads to invalid source folder and failed the compilation hence you cannot run the uncompiled code.

**Comment by eickhardt** [comment]
I see, thank you for the clarification!

**Comment by Ingli** [comment]
I ran into the same problem. Since I believe that this is an issue that many users of Javatar are confronted with, may I suggest to add a function "Build from scratch", or "Clean up project" or so. This way, we may be able to rebuild the project and run it.

**Comment by spywhere** [comment]
By default, Javatar always recompile the files (base on what you choose in the build dialog). But in v2.0.0 Javatar now compile only the file that has been changed (base on modified time) so I will add the clean up for Javatar 2.0.0 for this.

**Comment by Ingli** [comment]
Thanks a lot! I think I'm getting closer to what the issue is. Javatar, in its current version may not handle CLASSPATH entirely correct. Try to build a complex project with several directories and packages and then compile and run a single class inside a package. The separation of /bin and /src may cause the problem or changing package paths in the shell/directory manager. Some basic directory function such as move or copy could help.
Does Javatar move into /bin and use the package syntax correctly? Using java -cp .: package.MyClass in the shell in /bin works fine after compiling with Javatar. For this, it would be great if there was a little window in ST3 where we can see which shell commands are executed. Just saying... I like Javatar! Great contribution!

**Comment by spywhere** [comment]
Javatar does offer you a output directory by changing the `build_output_location` in the settings file.

Sadly, Javatar v1.0 does not show an actual command anywhere (but v2.0 does show in the console). However, you can take a look at an overview of the full command in the `build_command ` or `run_command` option in the settings file.

The commands that Javatar building up can be varies based on the settings you choose. Just like when you try to compile a file on your desktop but currently you are in the document directory since Javatar have `build_location` and `run_location` to specify a working directory for the command to be used.

Hope this might answer some of your questions on that.

**Comment by spywhere** [comment]
If possible, could you try using v2.0 instead and evaluate how Javatar should be improve?

I really want the v2.0 to suits the larger project (not as large as Maven or Gradle project, but that would be a great addition to add). So, right now v1.0 is really slow due to how the Javatar compile the files and also lack the supports for multiple source folders and some of the improvements that would be useful.

Currently, I working on an auto-completion feature and when it finished, the v2.0 is almost ready to me. So, if any addition could be add in the first release of v2.0, that would be great.

**Comment by wubin1989** [comment]
how to 'save it to the (.sublime-project)' ??
