### ISSUE TITLE
Adding natives

### ISSUE THREAD

**Issue by z3t0** [spywhere/Javatar#46]
How can I inject natives (dlls) for LWJGL using this build system? Thanks

**Comment by spywhere** [comment]
Javatar does not supports native injection out of the box. However, you can configure the run command to add your own flags for native injection for particular project by adjust the `run_command` value in your project file.

**Comment by spywhere** [comment]
Please bear with me since I'm working on another project at this moment which make Javatar less frequent to update. After September, I should be free enough to continue working on a v2.0 of Javatar (which exactly the same as v1.0 but better in term of performances, stability, etc.) and add this to the Javatar itself.

**Comment by z3t0** [comment]
@spywhere Sounds great! In the meantime I will try to figure it out (as my project depends on it). If you have any ideas as to how I can do this please let me know. For example I tried `Djava.library.path` as a program argument but it did not seem to work.

**Comment by spywhere** [comment]
Here I am setting up Javatar for LWJGL project, https://youtu.be/v-bWVrX8rzg

**Comment by spywhere** [comment]
This feature was implemented in Javatar v2.0.0-prebeta.
