### ISSUE TITLE
Javatar Shell EOF

### ISSUE THREAD

**Issue by YujiShen** [spywhere/Javatar#47]
Hi, I am using the `scanner.hasNext()` as the condition of a while loop to get input, but this method seems need a EOF to end the input. I do not know how to send an EOF in Javatar shell, I tried Ctrl+d and Ctrl+z no good. Any solution? Thanks.

**Comment by spywhere** [comment]
Sadly, Javatar cannot send EOF signal to the shell at this moment. You could modified the `utils/javatar_shell.py` file to close the input pipe on hotkey but in the meantime, I have to take this suggestion and implements it in v2.0 instead because it's a big impact with the (Javatar's) shell design.

**Comment by spywhere** [comment]
This feature was implemented in Javatar v2.0.0-prebeta.

To send the EOF signal, just clear the console (by select all and delete).
