### ISSUE TITLE
setting the source folder

### ISSUE THREAD

**Issue by scphantm** [spywhere/Javatar#5]
In my series of projects, i need to set the source folder.  I can't do it in my user settings because one project it could be /src, another its /src/main/java, and another one its /javasource

How do i use the project properties file to set the source folder?

**Comment by spywhere** [comment]
This issue is reopened since Javatar v2.0 will supports multiple source folders.

**Comment by spywhere** [comment]
The feature is implemented and available on Javatar v.2.0.0-prealpha

**Comment by SgtPooki** [comment]
I installed javatar via package control and anytime I try to set source folder, I get the spinning pinwheel of death. Mac osx El Capitan. 

EDIT: Just found that in the settings you can set the source folder via the project_data['2'].javatar.source_folder path:

```

    "project_data":
    {
        "2":
        {
            "folders":
            [
                {
                    "path": "/Volumes/Unix/code/projectFolder1"
                },
                {
                    "path": "/Users/sgt/code/projectFolder2"
                }
            ],
            "javatar":
            {
                "source_folder": "/Volumes/Unix/code/projectWorkspace/src/projectFolder1/src"
            }
        }
    }
```

EDIT: Nevermind, that doesn't work because it keeps getting overridden to some other folder that has no java code.

**Comment by spywhere** [comment]
The command for setting the source folder is also do what you just did, add the folder path as a `source_folder` option. However, Javatar v2.0.0 works differently since it supports multiple source folders.

Javatar prefer to have a single folder opened in one window as one project, then you can add the subfolder as a source folder.
