### ISSUE TITLE
defalt key-map "ctrl+shift+k" can't be override by user setting

### ISSUE THREAD

**Issue by Nicholas-Alam** [spywhere/Javatar#59]
Dear team,

As we all know the "ctrl+shift+k" shortcut is set default as "delete one line" in sublime's key-map,
But  "ctrl+shift+k" has been override by Javatar's default key-binding.  I can't use "ctrl+shift+k" to delete one single line after installed Javatar.
I tried to override Javatar's default key-binding by setting user  key-binding like this:
    {
        "keys": ["ctrl+shift+t","ctrl+shift+m"],
        "command": "javatar_util",
        "args": {
            "util_type": "parse",
            "text": "#"
        }
But still can't use "ctrl+shift+k" to delete lines.
could you pls help with this?

**Comment by spywhere** [comment]
If you override your `delete line` to `Ctrl+Shift+K`, this may not work since Javatar key bindings always begin with `Ctrl+Shift+K`. So why the overriding key does not work? Because when you press `Ctrl+Shift+K`, Sublime Text is still confuse of which commands you are going to use since `delete line` has bind with `Ctrl+Shift+K` but also many remaining Javatar commands still begin with `Ctrl+Shift+K` so Sublime Text might decide to wait for another key combination. Hence, the override is not working.

To solve this issue you have 2 options...

First option, you need to override `delete line` to a new key binding that is not `Ctrl+Shift+K`.

Second option, you need to override all Javatar commands to a new key binding that is not `Ctrl+Shift+K`.

You can see what commands Javatar has in the `Default (Platform).sublime-keymap` file.
