### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by aniknafs** [spywhere/Javatar#68]
I am using Sublime Text 3 on OS X 10.11, when I try to build my Java project I get this error:
sudo: no tty present and no askpass program specified

Any idea how to fix it?

**Comment by spywhere** [comment]
Javatar shell's does not supports some of the command since it's not a terminal emulator. Javatar utilise the process spawning to run your program and pipe the input/output from/to it. All of these leads to some functionalities are unsupported such as `sudo`.

If you can, please try compile your project using `javac` and check if it works properly or not. Sometimes it's hard to identify whether it's Javatar problem or the code itself.

If this issue is not related to that, please reopen issue and send me your Action History (`Cmd+Shift+K, Cmd+Shift+H`), Console logs (`View -> Show Console`) and if possible, screenshot with the correspond message.
