### ISSUE TITLE
Unable to create anythin

### ISSUE THREAD

**Issue by ghost** [spywhere/Javatar#69]
After installing through package control on Windows, I tried creating something. Nothing worked. Got the error "Cannot specify package location" every time. I'm noticing, though, that I don't have the side bar with the folders as in the screenshots.

**Comment by spywhere** [comment]
In order to working with Javatar, you will need to create a project (or folder and open it) in Sublime Text. Otherwise, Javatar would not know where to properly put your source code and your compiled code.

Take a look at the [Getting Started](https://javatar.readthedocs.io/en/latest/getting_started.html) for a overall usage of Javatar or learn more about [how Javatar detect default package](https://javatar.readthedocs.io/en/latest/default_packages.html).
